"""Initial migration for database tables for users and schedules

Revision ID: 421f7375ebdb
Revises: 
Create Date: 2024-09-19 10:54:50.678401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '421f7375ebdb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=256), nullable=False),
    sa.Column('schedule', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('schedule')
    # ### end Alembic commands ###
