"""Fix schedule table to have same user assigned to multiple schedules

Revision ID: 9ed75cae8489
Revises: e8749535337d
Create Date: 2024-09-10 20:30:06.642827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ed75cae8489'
down_revision = 'e8749535337d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_index('user_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.create_index('user_name', ['user_name'], unique=True)

    # ### end Alembic commands ###
